### ISSUE TITLE
Todo: Fix critical rules

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Attack-Improvement-Mod#9]
Some crit ideas:

- [x] Adjust normal crit chance range.
- [x] Turret and Vehicle crit chance multiplier.
- [ ] ~~Number or percentage of empty slots to ignore at each location.~~ May be when requested.
- [x] Allow vehicle and turret crit. 
- [x] Allow shots to deal critical "through" destroyed location. e.g. If a shot lands on a destroyed arm, it should trigger crit on the side torso or center torso.
- [ ] ~~Allow each shot to have a crit chance, instead of one per damaged location per weapon.~~ Replaced by:
- [x] Allow multiple crit per weapon.
- - [x] Min damage to trigger a crit, can be set to fixed number fixed or percentage of full structure.
- [x] Allow attack to trigger crit through armour:
- - [x] Min damage to crit through armour, can be set to fixed number or percentage of full armour.
- - [x] Max pass through percentage. This is multiplied to ( armour / max armour ) to get base crit chance before weapon and other modifiers.

- [ ] ~~Unrelated to crit, but I may as well add min head hit damage.~~ Don't waste my time.

**Comment by janxious** [comment]
For vehicles, there a number of status effects that don't exist in the game I had planned to take a swing at. These things have analogs in mechs and turrets, but vehicles are the ones that made me angry in the vanilla game. CBT rules: http://www.sarna.net/wiki/CBT_Ground_Vehicle_Critical_Hits_Table

**Comment by Sheep-y** [comment]
A crit system replacement has been developed, with vehicle and turret ceit, through armoir crit, crit ignore empty slot and destroyed component, crit location transfer, control of crit chance and npc multipliers by friend/foe, and is integrated with the mod's attack log.

It needs some more testing, esp. compatibility with MechEngineer, but the overall system structure is stable and not expecting to see big change between now and release.
